# Generated by Django 6.1 on 2026-08-25 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Area solicitante',
                'verbose_name_plural': 'Areas solicitantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveSmallIntegerField(help_text='Menor numero = mayor prioridad. Se usa para ordenar listados.')),
                ('sla_primera_respuesta_horas', models.PositiveIntegerField()),
                ('sla_resolucion_horas', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('L1', 'Soporte L1'), ('L2', 'Soporte L2'), ('GERENCIA', 'Gerencia (solo lectura)')], default='L1', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=12, unique=True)),
                ('tipo_solicitud', models.CharField(choices=[('INCIDENCIA', 'Incidencia'), ('REQUERIMIENTO', 'Requerimiento')], max_length=15)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('solicitante_nombre', models.CharField(max_length=120)),
                ('solicitante_email', models.EmailField(max_length=254)),
                ('canal_origen', models.CharField(choices=[('WEB', 'Formulario web'), ('EMAIL', 'Correo electronico')], max_length=10)),
                ('email_thread_id', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('ASIGNADO', 'Asignado'), ('EN_PROGRESO', 'En progreso'), ('ESPERANDO_USUARIO', 'Esperando al usuario'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], db_index=True, default='NUEVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_primera_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('solucion_aplicada', models.TextField(blank=True)),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='tickets.agente')),
                ('area_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.areasolicitante')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.categoria')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.prioridad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('ASIGNADO', 'Asignado'), ('EN_PROGRESO', 'En progreso'), ('ESPERANDO_USUARIO', 'Esperando al usuario'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('NUEVO', 'Nuevo'), ('ASIGNADO', 'Asignado'), ('EN_PROGRESO', 'En progreso'), ('ESPERANDO_USUARIO', 'Esperando al usuario'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.agente')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaCSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], null=True)),
                ('comentario', models.TextField(blank=True)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('respondido_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_csat', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Encuesta CSAT',
                'verbose_name_plural': 'Encuestas CSAT',
            },
        ),
        migrations.CreateModel(
            name='ArticuloKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('sintoma', models.TextField(help_text='Como se manifiesta el problema')),
                ('solucion', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Palabras clave separadas por coma', max_length=255)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.agente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_kb', to='tickets.categoria')),
                ('ticket_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_generados', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Articulo de base de conocimiento',
                'verbose_name_plural': 'Articulos de base de conocimiento',
                'ordering': ['-actualizado_at'],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/')),
                ('subido_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.agente')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket')),
            ],
        ),
    ]
