# Generated by Django 6.1 on 2026-08-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_seed_catalogos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='canal_origen',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email_thread_id',
        ),
    ]
